apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nw1tdisc8-python
  janus-idp.io/tekton: nw1tdisc8-python
  backstage.io/kubernetes-id: nw1tdisc8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nw1tdisc8-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
